export const EMPTY_INPUT = 'emptyInput'
export const MAX_DECIMAL_PART = 'maxDecimalPart'
export const MAX_NUMBER_PART = 'maxNumberPart'
export const ONLY_DECIMAL_DOT = 'onlyDecimalDot'
export const ONLY_NUMBER_PART = 'onlyNumberPart'
